# Generated by Django 5.2.1 on 2025-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="codeforces_handle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
