# Generated by Django 5.2.1 on 2025-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_codeforces_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="degree",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_cv",
            field=models.EmailField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="profile",
            name="name_cv",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="previous_work",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="school",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
