# Generated by Django 5.2.1 on 2025-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_solvedproblem"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicequestions",
            name="question_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
