# Generated by Django 5.2.1 on 2025-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_practicequestions_question_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicequestions",
            name="question_number",
            field=models.IntegerField(unique=True),
        ),
    ]
