# Generated by Django 5.2.1 on 2025-07-26 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_department_semester_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="e.g Unit 1", verbose_name=1000),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="subject_files/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "pptx", "xlsx"]
                            )
                        ],
                    ),
                ),
                ("uploaded_to", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="academics.subject",
                    ),
                ),
            ],
        ),
    ]
