# Generated by Django 5.2.1 on 2025-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_subjectfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="SubjectFile",
        ),
    ]
