# Generated by Django 5.2.1 on 2025-07-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_subject_url_delete_subjectfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.department",
            ),
            preserve_default=False,
        ),
    ]
