# Generated by Django 5.2.1 on 2025-08-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_semester_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturevideo",
            name="youtube_url",
            field=models.URLField(
                help_text="Paste full YouTube URL (e.g. https://youtu.be/xyz)"
            ),
        ),
        migrations.CreateModel(
            name="PythonTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Use basic HTML or rich text for formatting."
                    ),
                ),
                ("example_code", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="topics/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional embedded video URL (YouTube etc.)",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="academics.course",
                    ),
                ),
            ],
        ),
    ]
