# Generated by Django 5.2.1 on 2025-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_lecturevideo_youtube_url_pythontopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythontopic",
            name="show_compiler",
            field=models.BooleanField(default=True),
        ),
    ]
