# Generated by Django 5.2.1 on 2025-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_pythontopic_show_compiler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pythontopic",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Use basic HTML or rich text for formatting.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pythontopic",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
