# Generated by Django 5.2.1 on 2025-08-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_alter_pythontopic_content_alter_pythontopic_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("option1", models.CharField(max_length=255)),
                ("option2", models.CharField(max_length=255)),
                ("option3", models.CharField(blank=True, max_length=255, null=True)),
                ("option4", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "correct_option",
                    models.CharField(
                        choices=[
                            ("1", "Option 1"),
                            ("2", "Option 2"),
                            ("3", "Option 3"),
                            ("4", "Option 4"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="academics.course",
                    ),
                ),
            ],
        ),
    ]
