# Generated by Django 5.2.1 on 2025-09-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="page_number",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
